### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by ghost** [kkozemjakins/Spisok_produktov#1]
## Kopskats
Kods izskatās labi, 'usage conventions' tiek ievēroti, taču dažās vietās `id` un `class` tiek rakstīti dažādās valodās, kā arī ir vietas kur tiek izmantotas dubultās ķepiņas (`""`) un vietas, kur tiek izmantotas parastās ķepiņas jeb apostrofi (`''`). Iecerētā izdzēšanas funkcija vēl nebija gatava, bet tam nepievērsu uzmanību. Kopumā labi.

### JavaScript
JS failā atkārtoti bija uzrakstītas divas vienādas funkcijas, un otrai nav jēgas.
https://github.com/kkozemjakins/Spisok_produktov/blob/4ca6b48ed7c3572970e636cf36b7cd0ca57327fb/js/script.js#L5-L14

Īsti nezinu, vai šai rindai ir kāda funkcionalitāte, tāpēc no tās var atbrīvoties, ja nav cits iemesls.
https://github.com/kkozemjakins/Spisok_produktov/blob/4ca6b48ed7c3572970e636cf36b7cd0ca57327fb/js/script.js#L32

Šo 'if' var izveidot mazāku, apvienojot pirmos divus kopā un otro pārtaisot par 'else', taču tā nav kļūda.
https://github.com/kkozemjakins/Spisok_produktov/blob/4ca6b48ed7c3572970e636cf36b7cd0ca57327fb/js/script.js#L37-L45

### CSS un HTML
HTML struktūra ir laba, viegli maināma un pārlasāma. Taču, ne katram elementam vajag identifikatoru `id`. Ja nav īpašas stila vajadzības elementam, tad labāk ir izmantot vai nu 'class', vai atstāt bez sava identifikatora.
`<p></p>` vai `<p class="klase"></p>` var izmantot `<p id="identifikators"></p>` vietā.

CSS failā atkārtojās vienādi stila elementi, kurus var apvienot vienā ar komatu
https://github.com/kkozemjakins/Spisok_produktov/blob/4ca6b48ed7c3572970e636cf36b7cd0ca57327fb/css/style.css#L30-L42
(Pirmajā koda rindiņā var lietot `#submit_button_div, #input_place_div {`)

Ja ir par ko piebilst, var droši rakstīt komentāros.

**Comment by kkozemjakins** [comment]
Paldies)
